name: Compile Sketch

# The workflow will run on every push and pull request to the repository
on:
  - push
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v4

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          # The default is to compile for the Arduino Uno board. If you want to compile for other boards, use the `fqbn` input.
          fqbn: arduino:megaavr:uno2018
          sketch-paths: |
            # Configure the action to search all files under the root of the repository for sketches and compile them.
            # This is formatted as a YAML list, which makes it possible to have multiple sketch paths if needed.
            - ./sketches/wifi_moisture_sensor_ssr_pump_4_terminals_mqtt
            - ./sketches/wifi_moisture_sensor_ssr_pump_4_terminals
            - ./sketches/wifi_moisture_sensor_relay_pump_4_terminals
            - ./sketches/moisture_sensor_relay_pump_4_terminals
            - ./sketches/feather_moisture_sensor_relay_pump
          libraries: |
            # If the sketch being compiled doesn't use any libraries, so just use an empty list
            - name: WiFiNINA_Generic
            - name: ArduinoMqttClient
